### PR TITLE
Wrap mode switch

### PR DESCRIPTION
**Pull request by rakuyoMo**
## Added

- Add the function of not automatically wrapping lines, and you can switch between wrapping and not wrapping at any time.
- Moved the logic of "assembling attributed string from JSON slices" from JSONPreview into JSONDecorator. So you can now display JSON with the help of other text frames.

## Changed

- In order to achieve the non-wrapping function, the view hierarchy was modified.
- rename `LineNumberHeightManager` to `AttributedStringSizeCalculator`. (internal)
- UITableView sample supports tvOS.

### CODE REVIEW

**Comment by sjustfly** [comment]
@rakuyoMo But I encountered a problem where, when the JSON is very long, and I scroll to the bottom and collapse it, the top part goes missing.

**Comment by rakuyoMo** [comment]
> @rakuyoMo But I encountered a problem where, when the JSON is very long, and I scroll to the bottom and collapse it, the top part goes missing. [aaa.json](https://github.com/RakuyoKit/JSONPreview/files/14786545/aaa.json)

This may be an issue, I'm starting to investigate now. However, please confirm whether the json contains sensitive information. I am worried that it will cause trouble to you if you publish it publicly.

**Comment by sjustfly** [comment]
This is actually a regular JSON without any sensitive information.

**Comment by rakuyoMo** [comment]
@sjustfly This is an issue. I have reproduced it. It has nothing to do with your json. The json in the example will also trigger this problem. I think you'd better create a new issue separately

**Comment by rakuyoMo** [comment]
@sjustfly fixed by #23

**Pull request merged**
